server:
  port: 8081
spring:
  application:
    name: eureka-client2
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10 # 实例续约时间
    prefer-ip-address: true