#集群版本
server:
  port: 8763 #eureka的默认端口
spring:
  application:
    name: eureka-server  #应用名称
eureka:
  client:
    service-url: #不写 默认8761
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
  instance: #实例的配置
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} #主机名称:应用名称:端口号
    hostname: peer3 #主机名称 或服务的IP
    prefer-ip-address: true #以IP的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 10 #服务实例的续约的时间间隔